---
- name: Clone repository and copy files to Docker
  hosts: localhost
  tasks:
    - name: Clone GitHub repository
      ansible.builtin.git:
        repo: "https://github.com/dig24-bit/ycesproject.git"
        dest: /tmp/ycesproject
        version: main
        clone: yes
        update: yes

    - name: Verify repository contents
      ansible.builtin.debug:
        var: lookup('pipe', 'ls -la /tmp/ycesproject/')

    - name: Find files to copy
      ansible.builtin.find:
        paths: /tmp/ycesproject
        file_type: file
        recurse: yes
      register: files_to_copy

    - name: Debug files found
      ansible.builtin.debug:
        var: files_to_copy.files

    - name: Create target directory
      ansible.builtin.file:
        path: /target/path/
        state: directory
        mode: '0755'

    - name: Copy all files from repository
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/target/path/{{ item.path | basename }}"
        remote_src: yes
      loop: "{{ files_to_copy.files }}"
      when: files_to_copy.files | length > 0
